import {
  buildProjectMetadataPath,
  buildScriptResourceId,
  buildScriptZipPath
} from '../schema/projectSchema';
import type {
  BindingKey,
  CircleElement,
  GeneratedArtifacts,
  LineElement,
  PidsElement,
  PidsProject,
  RectElement,
  ResourcePackManifest,
  TextureElement,
  TextElement
} from '../types';
import { resolveBindingCode } from './bindings';
import { emitTextCall, emitTextureCall } from './jcmSpec';

function q(value: string) {
  return JSON.stringify(value);
}

function indent(value: string, level = 1) {
  const prefix = '  '.repeat(level);
  return value
    .split('\n')
    .map((line) => (line ? `${prefix}${line}` : line))
    .join('\n');
}

function round(value: number) {
  return Number(value.toFixed(3));
}

function literal(value: string | number | boolean) {
  if (typeof value === 'string') return q(value);
  if (typeof value === 'number') return String(round(value));
  return value ? 'true' : 'false';
}

export function colorToJcm(value: string | undefined, fallback = '#ffffff') {
  const color = /^#[0-9a-fA-F]{6}$/.test(value ?? '') ? value! : fallback;
  return `0x${color.slice(1).toUpperCase()}`;
}

export function getScriptFilename(project: PidsProject) {
  const parts = project.scriptPath.split('/');
  return parts[parts.length - 1] || 'custom_pids.js';
}

export function generateArtifacts(project: PidsProject): GeneratedArtifacts {
  return {
    script: generatePidsScript(project),
    scriptFilename: getScriptFilename(project),
    resourceJson: generateResourceJson(project),
    metadataFilename: buildProjectMetadataPath()
  };
}

export function buildResourcePackManifest(project: PidsProject): ResourcePackManifest {
  const scriptResourceId = buildScriptResourceId(project.resourceNamespace, project.scriptPath);
  const scriptZipPath = buildScriptZipPath(project.resourceNamespace, project.scriptPath);
  const projectMetadataPath = buildProjectMetadataPath();

  return {
    scriptResourceId,
    scriptZipPath,
    projectMetadataPath,
    files: [
      'joban_custom_resources.json',
      scriptZipPath,
      `assets/${project.resourceNamespace}/textures/block/pids/pixel.png`,
      `assets/${project.resourceNamespace}/textures/block/pids/circle.png`,
      ...project.assets.map((asset) => asset.zipPath),
      projectMetadataPath,
      'pack.mcmeta'
    ]
  };
}

export function generateResourceJson(project: PidsProject) {
  const manifest = buildResourcePackManifest(project);
  return JSON.stringify(
    {
      pids_images: [
        {
          id: safePresetId(project.name),
          name: project.name,
          scriptFiles: [manifest.scriptResourceId]
        }
      ]
    },
    null,
    2
  );
}

export function generatePidsScript(project: PidsProject) {
  const templateGroupId = 'rowTemplate';
  const absoluteElements = project.elements
    .filter((element) => element.visible && element.parentId !== templateGroupId)
    .sort((a, b) => a.z - b.z);

  const rowElements = project.elements
    .filter((element) => element.visible && element.parentId === templateGroupId && element.repeat?.enabled)
    .sort((a, b) => a.z - b.z);

  const metadata = embedProjectMetadata(project);
  const absoluteBody = absoluteElements.map((element) => indent(generateElement(element, 'absolute'), 1)).join('\n\n');
  const rowAlways = generateConditionalRowElements(rowElements, 'always');
  const rowArrival = generateConditionalRowElements(rowElements, 'arrival');
  const rowPlatform = generateConditionalRowElements(rowElements, 'platformVisible');
  const rowCustom = generateConditionalRowElements(rowElements, 'customMessage');

  return `// Generated by JS PIDS Visual Editor
// Preset: ${project.name}
// Target: ${project.preset}
// @js-pids-editor-project:${metadata}

function create(ctx, state, pids) {
  state.stationName = state.stationName || 'Central Station';
}

function render(ctx, state, pids) {
${indent(project.behavior.autoZOrdering ? `ctx.setAutoZOrdering?.(true);` : `ctx.setAutoZOrdering?.(false);\nctx.setZOrderStep?.(${round(project.behavior.zOrderStep)});`, 1)}
  const getArrival = (index) => {
    const entries = pids.arrivals && pids.arrivals();
    if (entries && typeof entries.get === 'function') return entries.get(index);
    return null;
  };
  const getCustomMessage = (index) => pids.getCustomMessage ? (pids.getCustomMessage(index) || '') : '';
  const isRowHidden = (index) => pids.isRowHidden ? Boolean(pids.isRowHidden(index)) : false;
  const isPlatformHidden = () => pids.isPlatformNumberHidden ? Boolean(pids.isPlatformNumberHidden()) : false;

${absoluteBody || '  // No absolute elements configured.'}

  drawRows(ctx, state, pids, getArrival, getCustomMessage, isRowHidden, isPlatformHidden);
}

function drawRows(ctx, state, pids, getArrival, getCustomMessage, isRowHidden, isPlatformHidden) {
${rowElements.map((element) => indent(generateRepeatedElement(element), 1)).join('\n\n') || '  // No repeated elements configured.'}
}

function dispose(ctx, state, pids) {
}

function drawRouteChip(ctx, x, y, size, color, label) {
  Texture.create('Route Chip BG')${emitTextureCall('texture', [q('jsblock:textures/block/pids/circle.png')])}${emitTextureCall('pos', ['x', 'y'])}${emitTextureCall('size', ['size', 'size'])}${emitTextureCall('color', ['normalizeColor(color, 0x1769D7)'])}${emitTextureCall('draw', ['ctx'])};

  Text.create('Route Chip Label')${emitTextCall('text', [`String(label || '')`])}${emitTextCall('pos', ['x', 'y + 1'])}${emitTextCall('size', ['size', 'size - 1'])}${emitTextCall('color', ['0xFFFFFF'])}${emitTextCall('centerAlign', [])}${emitTextCall('scale', ['1'])}${emitTextCall('bold', [])}${emitTextCall('draw', ['ctx'])};
}

function safeCall(obj, name, fallback) {
  if (!obj) return fallback;
  const value = obj[name];
  if (typeof value === 'function') {
    const result = value.call(obj);
    return result == null ? fallback : result;
  }
  return value == null ? fallback : value;
}

function getRouteColor(arrival, fallback) {
  const value = safeCall(arrival, 'routeColor', fallback);
  return normalizeColor(value, normalizeColor(fallback, 0x1769D7));
}

function normalizeColor(value, fallback) {
  if (typeof value === 'number') return value;
  if (typeof value === 'string') {
    if (value.startsWith('#')) return parseInt(value.slice(1), 16);
    if (/^[0-9a-fA-F]{6}$/.test(value)) return parseInt(value, 16);
  }
  return fallback;
}

function formatRouteDisplay(arrival, fallback) {
  if (!arrival) return fallback;
  const number = safeCall(arrival, 'routeNumber', '');
  const name = safeCall(arrival, 'routeName', '');
  return [number, name].filter(Boolean).join(' ') || fallback;
}

function formatEta(arrival, fallback) {
  if (!arrival) return fallback;
  if (safeCall(arrival, 'terminating', false)) return 'Terminating';
  const arrivalTime = String(safeCall(arrival, 'arrivalTime', ''));
  const minutes = arrivalTime.split(':')[1];
  if (!minutes) return fallback;
  const nowMinute = new Date().getMinutes();
  let diff = Number(minutes) - nowMinute;
  if (diff < 0) diff += 60;
  const deviation = Number(safeCall(arrival, 'deviation', 0));
  const suffix = deviation > 0 ? ' +' + deviation : deviation < 0 ? ' ' + deviation : '';
  return diff <= 0 ? 'Arr' : diff + ' min' + suffix;
}

function formatClock() {
  const now = new Date();
  return String(now.getHours()).padStart(2, '0') + ':' + String(now.getMinutes()).padStart(2, '0');
}
`;
}

function generateConditionalRowElements(elements: PidsElement[], condition: 'always' | 'arrival' | 'platformVisible' | 'customMessage') {
  return elements
    .filter((element) => {
      const current = element.condition ?? 'always';
      return current === condition;
    })
    .map((element) => indent(generateElement(element, 'row'), 1))
    .join('\n\n');
}

function generateRepeatedElement(element: PidsElement) {
  const repeat = element.repeat!;
  const rowCountExpr = `(${repeat.count})`;
  const stepX = repeat.direction === 'horizontal' ? round(element.w + repeat.gap) : 0;
  const stepY = repeat.direction === 'vertical' ? round(element.h + repeat.gap) : 0;
  const lines = [
    `for (let i = 0; i < ${rowCountExpr}; i += 1) {`,
    `  const rowX = ${round(element.x)} + i * ${stepX};`,
    `  const rowY = ${round(element.y)} + i * ${stepY};`,
    `  ${generateElement(element, 'row').replace(/^/gm, '  ')}`,
    `}`
  ];
  return lines.join('\n');
}

function generateElement(element: PidsElement, mode: 'absolute' | 'row') {
  switch (element.kind) {
    case 'text':
      return generateText(element, mode);
    case 'rect':
      return generateRect(element, mode);
    case 'texture':
      return generateTexture(element, mode);
    case 'line':
      return generateLine(element, mode);
    case 'circle':
      // Route Chip is temporarily disabled until its editor/export bugs are fixed.
      return '';
    default:
      return '';
  }
}

function generateText(element: TextElement, mode: 'absolute' | 'row') {
  const expression = resolveBindingExpression(element.binding, element, mode);
  const lines = [
    `Text.create(${q(element.name)})`,
    `  ${emitTextCall('text', [expression]).slice(1)}`,
    `  ${emitTextCall('pos', [textXExpression(element, mode), textYExpression(element, mode)]).slice(1)}`,
    `  ${emitTextCall('size', [literal(round(element.w)), literal(round(element.h))]).slice(1)}`,
    `  ${emitTextCall('color', [colorToJcm(element.color)]).slice(1)}`,
    `  ${emitTextCall('scale', [literal(element.fontSize / 5)]).slice(1)}`,
    element.font ? `  ${emitTextCall('font', [q(element.font)]).slice(1)}` : '',
    element.fontWeight === 'bold' ? `  ${emitTextCall('bold', []).slice(1)}` : '',
    element.italic ? `  ${emitTextCall('italic', []).slice(1)}` : '',
    element.shadow ? `  ${emitTextCall('shadowed', []).slice(1)}` : '',
    element.align === 'center' ? `  ${emitTextCall('centerAlign', []).slice(1)}` : '',
    element.align === 'right' ? `  ${emitTextCall('rightAlign', []).slice(1)}` : '',
    overflowCall(element),
    `  ${emitTextCall('draw', ['ctx']).slice(1)}`
  ].filter(Boolean);

  return lines.join('\n');
}

function generateRect(element: RectElement, mode: 'absolute' | 'row') {
  const lines = [
    `Texture.create(${q(element.name)})`,
    `  ${emitTextureCall('texture', [q('jsblock:textures/block/pids/pixel.png')]).slice(1)}`,
    `  ${emitTextureCall('pos', [textXExpression(element, mode), textYExpression(element, mode)]).slice(1)}`,
    `  ${emitTextureCall('size', [literal(round(element.w)), literal(round(element.h))]).slice(1)}`,
    `  ${emitTextureCall('color', [colorToJcm(element.fill)]).slice(1)}`,
    element.uv ? `  ${emitTextureCall('uv', element.uv.map((value) => literal(round(value)))).slice(1)}` : '',
    `  ${emitTextureCall('draw', ['ctx']).slice(1)}`
  ].filter(Boolean);
  return lines.join('\n');
}

function generateTexture(element: TextureElement, mode: 'absolute' | 'row') {
  const tint = element.tint ? colorToJcm(element.tint, '#ffffff') : '0xFFFFFF';
  const lines = [
    `Texture.create(${q(element.name)})`,
    `  ${emitTextureCall('texture', [q(element.textureId)]).slice(1)}`,
    `  ${emitTextureCall('pos', [textXExpression(element, mode), textYExpression(element, mode)]).slice(1)}`,
    `  ${emitTextureCall('size', [literal(round(element.w)), literal(round(element.h))]).slice(1)}`,
    `  ${emitTextureCall('color', [tint]).slice(1)}`,
    element.uv ? `  ${emitTextureCall('uv', element.uv.map((value) => literal(round(value)))).slice(1)}` : '',
    `  ${emitTextureCall('draw', ['ctx']).slice(1)}`
  ].filter(Boolean);
  return lines.join('\n');
}

function generateLine(element: LineElement, mode: 'absolute' | 'row') {
  return [
    `Texture.create(${q(element.name)})`,
    `  ${emitTextureCall('texture', [q('jsblock:textures/block/pids/pixel.png')]).slice(1)}`,
    `  ${emitTextureCall('pos', [textXExpression(element, mode), textYExpression(element, mode)]).slice(1)}`,
    `  ${emitTextureCall('size', [literal(round(element.w)), literal(round(Math.max(element.strokeWidth, 0.4)))]).slice(1)}`,
    `  ${emitTextureCall('color', [colorToJcm(element.stroke)]).slice(1)}`,
    `  ${emitTextureCall('draw', ['ctx']).slice(1)}`
  ].join('\n');
}

function generateCircle(element: CircleElement, mode: 'absolute' | 'row') {
  const label = resolveBindingExpression(element.binding ?? 'static', {
    kind: 'text',
    id: element.id,
    name: element.name,
    visible: element.visible,
    parentId: element.parentId,
    x: element.x,
    y: element.y,
    w: element.w,
    h: element.h,
    z: element.z,
    condition: element.condition,
    text: element.text ?? '',
    binding: element.binding ?? 'static',
    color: element.textColor ?? '#ffffff',
    fontSize: 5,
    fontWeight: 'bold',
    align: 'center',
    overflow: 'none',
    fallback: element.text ?? ''
  }, mode);

  const color = element.binding === 'arrival.routeNumber()' && mode === 'row'
    ? `getRouteColor(arrival, ${q(element.fill)})`
    : colorToJcm(element.fill);

  return `drawRouteChip(ctx, ${textXExpression(element, mode)}, ${textYExpression(element, mode)}, ${round(element.w)}, ${color}, ${label});`;
}

function resolveBindingExpression(binding: BindingKey, element: TextElement, mode: 'absolute' | 'row') {
  return resolveBindingCode(binding, {
    rowVar: mode === 'row' ? 'i' : String(element.rowIndex ?? 0),
    arrivalVar: 'arrival',
    customMessageVar: 'customMessage',
    platformHiddenVar: 'isPlatformHidden',
    fallbackExpression: q(element.fallback || element.text || '--'),
    colorFallback: element.color
  });
}

function overflowCall(element: TextElement) {
  switch (element.overflow) {
    case 'stretchXY':
      return `  ${emitTextCall('stretchXY', []).slice(1)}`;
    case 'scaleXY':
      return `  ${emitTextCall('scaleXY', []).slice(1)}`;
    case 'wrapText':
      return `  ${emitTextCall('wrapText', []).slice(1)}`;
    case 'marquee':
      return `  ${emitTextCall('marquee', element.marqueeDuration ? [literal(element.marqueeDuration)] : []).slice(1)}`;
    default:
      return '';
  }
}

function textYExpression(element: PidsElement, mode: 'absolute' | 'row') {
  return mode === 'row' ? `rowY + ${round(element.y)}` : literal(round(element.y));
}

function textXExpression(element: PidsElement, mode: 'absolute' | 'row') {
  return mode === 'row' ? `rowX + ${round(element.x)}` : literal(round(element.x));
}

function embedProjectMetadata(project: PidsProject) {
  const text = JSON.stringify(project);
  const bytes = new TextEncoder().encode(text);
  let binary = '';
  bytes.forEach((byte) => {
    binary += String.fromCharCode(byte);
  });
  return btoa(binary);
}

export function safePresetId(name: string) {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, '') || 'custom_pids';
}
