import type { PidsElement, PidsProject } from '../types';

let nextId = 1;

export function uid(prefix = 'el') {
  nextId += 1;
  return `${prefix}_${nextId.toString(36)}`;
}

export function safePresetId(name: string) {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, '') || 'custom_pids';
}

const elements: PidsElement[] = [
  {
    id: 'bg',
    kind: 'rect',
    name: 'Background',
    visible: true,
    parentId: 'root',
    x: 0,
    y: 0,
    w: 136,
    h: 76,
    z: 0,
    fill: '#08111f',
    stroke: '#41536f',
    radius: 1,
    textureId: 'jsblock:textures/block/pids/pixel.png'
  },
  {
    id: 'header_bg',
    kind: 'rect',
    name: 'Header Background',
    visible: true,
    parentId: 'header',
    x: 0,
    y: 0,
    w: 136,
    h: 14,
    z: 1,
    fill: '#0d1f3a',
    textureId: 'jsblock:textures/block/pids/pixel.png'
  },
  {
    id: 'station_title',
    kind: 'text',
    name: 'Station Title',
    visible: true,
    parentId: 'header',
    x: 18,
    y: 3,
    w: 74,
    h: 9,
    z: 2,
    text: 'Central Station',
    binding: 'stationName',
    color: '#ffffff',
    fontSize: 7,
    fontWeight: 'bold',
    align: 'left',
    overflow: 'none',
    fallback: 'Station',
    font: 'mtr:mtr'
  },
  {
    id: 'clock',
    kind: 'text',
    name: 'Clock',
    visible: true,
    parentId: 'header',
    x: 107,
    y: 3,
    w: 26,
    h: 9,
    z: 3,
    text: '10:24',
    binding: 'clock',
    color: '#ffffff',
    fontSize: 7,
    fontWeight: 'bold',
    align: 'right',
    overflow: 'none',
    fallback: '--:--',
    font: 'mtr:mtr'
  },
  {
    id: 'divider',
    kind: 'line',
    name: 'Header Divider',
    visible: true,
    parentId: 'header',
    x: 0,
    y: 14,
    w: 136,
    h: 0,
    z: 4,
    stroke: '#ffd32a',
    strokeWidth: 0.6
  },
  {
    id: 'col_route',
    kind: 'text',
    name: 'Route Label',
    visible: true,
    parentId: 'header',
    x: 5,
    y: 17,
    w: 18,
    h: 5,
    z: 5,
    text: 'Route',
    binding: 'static',
    color: '#ffd32a',
    fontSize: 4,
    fontWeight: 'bold',
    align: 'left',
    overflow: 'none',
    fallback: ''
  },
  {
    id: 'col_destination',
    kind: 'text',
    name: 'Destination Label',
    visible: true,
    parentId: 'header',
    x: 28,
    y: 17,
    w: 52,
    h: 5,
    z: 6,
    text: 'Destination',
    binding: 'static',
    color: '#ffd32a',
    fontSize: 4,
    fontWeight: 'bold',
    align: 'left',
    overflow: 'none',
    fallback: ''
  },
  {
    id: 'col_eta',
    kind: 'text',
    name: 'ETA Label',
    visible: true,
    parentId: 'header',
    x: 92,
    y: 17,
    w: 20,
    h: 5,
    z: 7,
    text: 'ETA',
    binding: 'static',
    color: '#ffd32a',
    fontSize: 4,
    fontWeight: 'bold',
    align: 'left',
    overflow: 'none',
    fallback: ''
  },
  {
    id: 'col_platform',
    kind: 'text',
    name: 'Platform Label',
    visible: true,
    parentId: 'header',
    x: 119,
    y: 17,
    w: 16,
    h: 5,
    z: 8,
    text: 'Platform',
    binding: 'static',
    color: '#ffd32a',
    fontSize: 4,
    fontWeight: 'bold',
    align: 'right',
    overflow: 'none',
    fallback: ''
  },
  {
    id: 'row_bg_template',
    kind: 'rect',
    name: 'Row Background',
    visible: true,
    parentId: 'rowTemplate',
    x: 0,
    y: -1.5,
    w: 136,
    h: 10.5,
    z: 10,
    fill: '#0c1522',
    opacity: 0.82,
    condition: 'always',
    textureId: 'jsblock:textures/block/pids/pixel.png'
  },
  {
    id: 'route_chip_template',
    kind: 'circle',
    name: 'Route Chip',
    visible: true,
    parentId: 'rowTemplate',
    x: 10,
    y: 0,
    w: 9,
    h: 9,
    z: 11,
    fill: '#1769d7',
    stroke: '#ffffff',
    text: 'A',
    textColor: '#ffffff',
    rowIndex: 0,
    binding: 'arrival.routeNumber()',
    condition: 'arrival',
    textureId: 'jsblock:textures/block/pids/circle.png'
  },
  {
    id: 'destination_template',
    kind: 'text',
    name: 'Destination',
    visible: true,
    parentId: 'rowTemplate',
    x: 28,
    y: 0,
    w: 54,
    h: 8,
    z: 12,
    text: 'Airport',
    binding: 'arrival.destination()',
    rowIndex: 0,
    color: '#ffffff',
    fontSize: 6.4,
    fontWeight: 'bold',
    align: 'left',
    overflow: 'scaleXY',
    fallback: '--',
    condition: 'arrival',
    font: 'mtr:mtr'
  },
  {
    id: 'eta_template',
    kind: 'text',
    name: 'ETA',
    visible: true,
    parentId: 'rowTemplate',
    x: 92,
    y: 0.7,
    w: 22,
    h: 6,
    z: 13,
    text: '2 min',
    binding: 'computed.etaText',
    rowIndex: 0,
    color: '#ffd32a',
    fontSize: 5.4,
    fontWeight: 'bold',
    align: 'left',
    overflow: 'none',
    fallback: '--',
    condition: 'arrival'
  },
  {
    id: 'platform_template',
    kind: 'text',
    name: 'Platform',
    visible: true,
    parentId: 'rowTemplate',
    x: 120,
    y: -0.5,
    w: 11,
    h: 7,
    z: 14,
    text: '1',
    binding: 'arrival.platformName()',
    rowIndex: 0,
    color: '#ffffff',
    fontSize: 6.5,
    fontWeight: 'bold',
    align: 'right',
    overflow: 'none',
    fallback: '--',
    condition: 'platformVisible'
  },
  {
    id: 'custom_message_bg_template',
    kind: 'rect',
    name: 'Custom Message Background',
    visible: true,
    parentId: 'rowTemplate',
    x: 2,
    y: -1.5,
    w: 132,
    h: 10.5,
    z: 15,
    fill: '#101419',
    stroke: '#6f7481',
    radius: 1.2,
    opacity: 0.95,
    condition: 'customMessage',
    textureId: 'jsblock:textures/block/pids/pixel.png'
  },
  {
    id: 'custom_message_template',
    kind: 'text',
    name: 'Custom Message Text',
    visible: true,
    parentId: 'rowTemplate',
    x: 8,
    y: 1,
    w: 120,
    h: 6,
    z: 16,
    text: 'Service Alert: Signal maintenance on Line B.',
    binding: 'pids.getCustomMessage(i)',
    rowIndex: 0,
    color: '#ffd32a',
    fontSize: 4.8,
    fontWeight: 'bold',
    align: 'left',
    overflow: 'marquee',
    marqueeDuration: 100,
    fallback: '',
    condition: 'customMessage'
  },
  {
    id: 'footer_left',
    kind: 'text',
    name: 'Footer Left',
    visible: true,
    parentId: 'footer',
    x: 5,
    y: 71.5,
    w: 60,
    h: 4,
    z: 32,
    text: 'Thank you for riding with us.',
    binding: 'static',
    color: '#bfc7d5',
    fontSize: 3.5,
    fontWeight: 'normal',
    align: 'left',
    overflow: 'none',
    fallback: ''
  },
  {
    id: 'footer_right',
    kind: 'text',
    name: 'Footer Right',
    visible: true,
    parentId: 'footer',
    x: 88,
    y: 71.5,
    w: 43,
    h: 4,
    z: 33,
    text: 'Have a nice day!',
    binding: 'static',
    color: '#d9b36c',
    fontSize: 3.5,
    fontWeight: 'normal',
    align: 'right',
    overflow: 'none',
    fallback: ''
  }
];

export function createDefaultProject(): PidsProject {
  nextId = 1000;
  return {
    schemaVersion: 2,
    name: 'Untitled PIDS Preset',
    preset: 'rv_pids',
    resourceNamespace: 'jsblock',
    scriptPath: 'scripts/pids/custom_pids.js',
    canvas: {
      width: 136,
      height: 76
    },
    repeatRows: {
      enabled: true,
      groupId: 'rowTemplate',
      name: 'Arrival Rows',
      startY: 24,
      rowHeight: 12,
      maxRows: 4,
      countSource: 'pids.rows',
      skipHiddenRows: true,
      collapseEmptyRows: true,
      customMessageMode: 'replace-row',
      showFallbackWhenEmpty: false
    },
    behavior: {
      respectCustomMessage: true,
      respectHidePlatformNumber: true,
      respectHideArrival: true,
      usePidsDimensions: true,
      autoZOrdering: true,
      zOrderStep: 0.0002
    },
    groups: [
      { id: 'root', name: 'Root', visible: true, children: ['bg'] },
      { id: 'header', name: 'Header', visible: true, children: ['header_bg', 'station_title', 'clock', 'divider', 'col_route', 'col_destination', 'col_eta', 'col_platform'] },
      { id: 'rowTemplate', name: 'Arrival Rows Template', visible: true, children: elements.filter((element) => element.parentId === 'rowTemplate').map((element) => element.id) },
      { id: 'footer', name: 'Footer', visible: true, children: ['footer_left', 'footer_right'] }
    ],
    elements: JSON.parse(JSON.stringify(elements)) as PidsElement[]
  };
}
