import {
  assertValidScriptPath,
  buildProjectMetadataPath,
  buildScriptZipPath,
  importJsonLikeText
} from '../schema/projectSchema';
import type { PidsProject, ProjectImportResult, ResourcePackBuildResult } from '../types';
import { buildResourcePackManifest, generateArtifacts } from './codegen';

const TEXT_ENCODER = new TextEncoder();
const PIXEL_PNG_BASE64 = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/p9sAAAAASUVORK5CYII=';

export function importProjectText(text: string): ProjectImportResult {
  return importJsonLikeText(text);
}

export async function buildResourcePackZip(project: PidsProject): Promise<ResourcePackBuildResult> {
  const artifacts = generateArtifacts(project);
  const manifest = buildResourcePackManifest(project);

  assertValidScriptPath(project.scriptPath);
  validateZipPath(manifest.scriptZipPath);

  const files: Record<string, Uint8Array> = {
    'joban_custom_resources.json': TEXT_ENCODER.encode(artifacts.resourceJson),
    [manifest.scriptZipPath]: TEXT_ENCODER.encode(artifacts.script),
    [`assets/${project.resourceNamespace}/textures/block/pids/pixel.png`]: base64ToBytes(PIXEL_PNG_BASE64),
    [`assets/${project.resourceNamespace}/textures/block/pids/circle.png`]: base64ToBytes(PIXEL_PNG_BASE64),
    [buildProjectMetadataPath()]: TEXT_ENCODER.encode(JSON.stringify(project, null, 2)),
    'pack.mcmeta': TEXT_ENCODER.encode(
      JSON.stringify(
        {
          pack: {
            pack_format: 15,
            description: `${project.name} generated by JS PIDS Visual Editor`
          }
        },
        null,
        2
      )
    )
  };

  Object.keys(files).forEach(validateZipPath);

  return {
    blob: new Blob([createZip(files)], { type: 'application/zip' }),
    manifest: {
      ...manifest,
      files: Object.keys(files)
    }
  };
}

export function getProjectMetadataFilename() {
  return buildProjectMetadataPath();
}

export function getScriptZipPath(project: PidsProject) {
  return buildScriptZipPath(project.resourceNamespace, project.scriptPath);
}

function validateZipPath(path: string) {
  const normalized = path.replace(/\\/g, '/');
  if (normalized.startsWith('/') || /^[a-zA-Z]:/.test(normalized)) {
    throw new Error(`ZIP path must be relative: ${path}`);
  }
  if (normalized.split('/').some((segment) => segment === '..' || segment === '.')) {
    throw new Error(`ZIP path cannot contain dot segments: ${path}`);
  }
}

function base64ToBytes(base64: string) {
  const binary = atob(base64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i += 1) bytes[i] = binary.charCodeAt(i);
  return bytes;
}

function createZip(files: Record<string, Uint8Array>) {
  const localParts: Uint8Array[] = [];
  const centralParts: Uint8Array[] = [];
  let offset = 0;

  Object.entries(files).forEach(([name, content]) => {
    const nameBytes = TEXT_ENCODER.encode(name);
    const crc = crc32(content);
    const localHeader = new Uint8Array(30 + nameBytes.length);
    const local = new DataView(localHeader.buffer);
    local.setUint32(0, 0x04034b50, true);
    local.setUint16(4, 20, true);
    local.setUint16(6, 0, true);
    local.setUint16(8, 0, true);
    local.setUint16(10, 0, true);
    local.setUint16(12, 0, true);
    local.setUint32(14, crc, true);
    local.setUint32(18, content.length, true);
    local.setUint32(22, content.length, true);
    local.setUint16(26, nameBytes.length, true);
    local.setUint16(28, 0, true);
    localHeader.set(nameBytes, 30);
    localParts.push(localHeader, content);

    const centralHeader = new Uint8Array(46 + nameBytes.length);
    const central = new DataView(centralHeader.buffer);
    central.setUint32(0, 0x02014b50, true);
    central.setUint16(4, 20, true);
    central.setUint16(6, 20, true);
    central.setUint16(8, 0, true);
    central.setUint16(10, 0, true);
    central.setUint16(12, 0, true);
    central.setUint16(14, 0, true);
    central.setUint32(16, crc, true);
    central.setUint32(20, content.length, true);
    central.setUint32(24, content.length, true);
    central.setUint16(28, nameBytes.length, true);
    central.setUint16(30, 0, true);
    central.setUint16(32, 0, true);
    central.setUint16(34, 0, true);
    central.setUint16(36, 0, true);
    central.setUint32(38, 0, true);
    central.setUint32(42, offset, true);
    centralHeader.set(nameBytes, 46);
    centralParts.push(centralHeader);

    offset += localHeader.length + content.length;
  });

  const centralOffset = offset;
  const centralSize = centralParts.reduce((sum, item) => sum + item.length, 0);
  const end = new Uint8Array(22);
  const endView = new DataView(end.buffer);
  endView.setUint32(0, 0x06054b50, true);
  endView.setUint16(8, Object.keys(files).length, true);
  endView.setUint16(10, Object.keys(files).length, true);
  endView.setUint32(12, centralSize, true);
  endView.setUint32(16, centralOffset, true);

  return concatBytes([...localParts, ...centralParts, end]);
}

function concatBytes(parts: Uint8Array[]) {
  const length = parts.reduce((sum, part) => sum + part.length, 0);
  const output = new Uint8Array(length);
  let offset = 0;
  parts.forEach((part) => {
    output.set(part, offset);
    offset += part.length;
  });
  return output;
}

function crc32(bytes: Uint8Array) {
  let crc = 0xffffffff;
  for (let i = 0; i < bytes.length; i += 1) {
    crc ^= bytes[i];
    for (let j = 0; j < 8; j += 1) {
      crc = (crc >>> 1) ^ (0xedb88320 & -(crc & 1));
    }
  }
  return (crc ^ 0xffffffff) >>> 0;
}
